from datetime import datetime

def generate_html(target, os_guess, ports, results):

    rows = ""
    for r in results:
        risk  = r.get("risk", "INFO")
        color = {"HIGH": "#ff4444", "MEDIUM": "#ffaa00",
                 "LOW": "#4488ff", "INFO": "#44bb44"}.get(risk, "#888")

        cve_html = ""
        if r.get("cves"):
            cve_html = "<div style='margin-top:8px'>"
            for cve in r["cves"]:
                try:
                    score = float(cve["score"])
                except:
                    score = 0
                sc = "#ff4444" if score >= 7 else "#ffaa00" if score >= 4 else "#44bb44"
                cve_html += (
                    "<div style='background:#0d1117;border-radius:6px;"
                    "padding:8px 12px;margin-bottom:6px;"
                    "border-left:3px solid " + sc + "'>"
                    "<span style='color:" + sc + ";font-weight:600;font-size:13px'>"
                    + cve['id'] + "</span>"
                    "<span style='color:#888;font-size:12px;margin-left:8px'>CVSS: "
                    + str(cve['score']) + "</span>"
                    "<div style='color:#aaa;font-size:12px;margin-top:4px'>"
                    + cve['description'] + "</div></div>"
                )
            cve_html += "</div>"
        else:
            cve_html = "<span style='color:#44bb44;font-size:13px'>No CVEs found</span>"

        rows += (
            "<tr>"
            "<td style='font-weight:600'>" + str(r['port']) + "</td>"
            "<td><span style='color:#44bb44;font-weight:600'>OPEN</span></td>"
            "<td>" + r['service'] + "</td>"
            "<td style='color:#888'>" + r['banner'] + "</td>"
            "<td><span style='color:" + color + ";font-weight:600'>" + risk + "</span></td>"
            "<td>" + r.get('vuln_desc', '') + "</td>"
            "</tr>"
            "<tr><td colspan='6' style='padding:4px 16px 16px 16px;"
            "background:#0d1117'>" + cve_html + "</td></tr>"
        )

    total_cves = sum(len(r.get("cves", [])) for r in results)
    high_ports = sum(1 for r in results if r.get("risk") == "HIGH")
    scan_time  = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    no_data = ("<tr><td colspan='6' style='text-align:center;"
               "color:#555;padding:24px'>No open ports found</td></tr>")

    html = (
        "<!DOCTYPE html><html lang='en'><head>"
        "<meta charset='UTF-8'>"
        "<title>Scan Report - " + target + "</title>"
        "<style>"
        "body{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;margin:0;padding:30px}"
        "h1{color:#58a6ff;margin-bottom:6px}"
        ".sub{color:#888;font-size:13px;margin-bottom:24px}"
        ".meta{background:#161b22;padding:16px 20px;border-radius:8px;margin-bottom:24px;border:1px solid #30363d}"
        ".meta span{color:#58a6ff;font-weight:600}"
        ".stats{display:flex;gap:16px;margin-bottom:24px}"
        ".stat{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:14px 20px;flex:1;text-align:center}"
        ".stat .num{font-size:28px;font-weight:600;color:#58a6ff}"
        ".stat .lbl{font-size:12px;color:#888;margin-top:2px}"
        "table{width:100%;border-collapse:collapse;background:#161b22;border-radius:8px;overflow:hidden}"
        "th{background:#21262d;padding:12px 16px;text-align:left;color:#58a6ff;font-size:12px;text-transform:uppercase;letter-spacing:.5px}"
        "td{padding:12px 16px;border-top:1px solid #21262d;font-size:14px;vertical-align:top}"
        ".footer{margin-top:24px;font-size:12px;color:#555}"
        "</style></head><body>"
        "<h1>Network Scan Report</h1>"
        "<div class='sub'>Generated by Basic Network Scanner v4.0</div>"
        "<div class='meta'>"
        "<p>Target: <span>" + target + "</span></p>"
        "<p>OS Guess: <span>" + os_guess + "</span></p>"
        "<p>Ports Scanned: <span>" + ports + "</span></p>"
        "<p>Scan Time: <span>" + scan_time + "</span></p>"
        "</div>"
        "<div class='stats'>"
        "<div class='stat'><div class='num'>" + str(len(results)) + "</div>"
        "<div class='lbl'>Open Ports</div></div>"
        "<div class='stat'><div class='num' style='color:#ff4444'>" + str(high_ports) + "</div>"
        "<div class='lbl'>High Risk</div></div>"
        "<div class='stat'><div class='num' style='color:#ffaa00'>" + str(total_cves) + "</div>"
        "<div class='lbl'>CVEs Found</div></div>"
        "</div>"
        "<table>"
        "<tr><th>Port</th><th>Status</th><th>Service</th>"
        "<th>Banner</th><th>Risk</th><th>Notes / CVEs</th></tr>"
        + (rows if rows else no_data) +
        "</table>"
        "<div class='footer'>Basic Network Scanner v4.0 — For authorized testing only</div>"
        "</body></html>"
    )

    return html