from datetime import datetime

def generate_html(target, os_guess, ports, results):
    """Generate a beautiful HTML report."""

    rows = ""
    for r in results:
        risk  = r.get("risk", "INFO")
        color = {"HIGH": "#ff4444", "MEDIUM": "#ffaa00",
                 "LOW": "#4488ff", "INFO": "#44bb44"}.get(risk, "#888")
        rows += f"""
        <tr>
            <td>{r['port']}</td>
            <td><span style='color:#44bb44;font-weight:600'>OPEN</span></td>
            <td>{r['service']}</td>
            <td>{r['banner']}</td>
            <td><span style='color:{color};font-weight:600'>{risk}</span></td>
            <td style='font-size:13px;color:#aaa'>{r['vuln_desc']}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='UTF-8'>
<title>Scan Report - {target}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117;
          color: #c9d1d9; margin: 0; padding: 30px; }}
  h1   {{ color: #58a6ff; }}
  .meta {{ background: #161b22; padding: 16px 20px;
           border-radius: 8px; margin-bottom: 24px;
           border: 1px solid #30363d; }}
  .meta span {{ color: #58a6ff; font-weight: 600; }}
  table {{ width: 100%; border-collapse: collapse;
           background: #161b22; border-radius: 8px;
           overflow: hidden; }}
  th    {{ background: #21262d; padding: 12px 16px;
           text-align: left; color: #58a6ff;
           font-size: 13px; text-transform: uppercase;
           letter-spacing: 0.5px; }}
  td    {{ padding: 12px 16px; border-top: 1px solid #21262d;
           font-size: 14px; }}
  tr:hover td {{ background: #1c2128; }}
  .footer {{ margin-top: 24px; font-size: 12px; color: #555; }}
</style>
</head>
<body>
<h1>Network Scan Report</h1>
<div class='meta'>
  <p>Target: <span>{target}</span></p>
  <p>OS Guess: <span>{os_guess}</span></p>
  <p>Ports Scanned: <span>{ports}</span></p>
  <p>Scan Time: <span>{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</span></p>
</div>
<table>
  <tr>
    <th>Port</th><th>Status</th><th>Service</th>
    <th>Banner</th><th>Risk</th><th>Notes</th>
  </tr>
  {rows if rows else "<tr><td colspan='6' style='text-align:center;color:#555'>No open ports found</td></tr>"}
</table>
<div class='footer'>Generated by Basic Network Scanner v3.0</div>
</body>
</html>"""

    return html